### PR TITLE
fix: dropdown should not close on inside click when autoClose is 'outside'

### LINKED ISSUE #59: Dropdown should not close on inside click when autoClose is 'outside'

### PR DESCRIPTION
**Pull request by bobbyg603**
Fixes #59

### CODE REVIEW

**Comment by bobbyg603** [comment]
will review with @daveplunkett tomorrow

File: projects/ngb-filterable-dropdown/src/lib/ngb-custom-filterable-dropdown/ngb-custom-filterable-dropdown.component.ts [hunk 1]
```diff
@@ -187,8 +187,6 @@ export class NgbCustomFilterableDropdownComponent implements OnInit, OnDestroy {
       event.stopPropagation();
```
Comment (bobbyg603) [inline projects/ngb-filterable-dropdown/src/lib/ngb-custom-filterable-dropdown/ngb-custom-filterable-dropdown.component.ts:187]: Remove this, we got rid of it :)

**Comment by daveplunkett** [comment]
We did the retroactive code review on this today.  Looks great!
